### ISSUE TITLE
transform: scale()在手机上预览貌似不起作用

### ISSUE THREAD

**Issue by fancyallen** [xiaolin3303/wx-charts#1]
如题
开发工具中调试，是好用的，放在手机上预览还是很大，不知道怎么回事。
这是我的样式，别的都和您例子里的一样的，transform-origin是起作用的， transform不起作用
`.canvas {
    width: 640px;
    height: 600px;
    transform: scale(0.5);
    transform-origin: 0% 0%;
}`

**Comment by xiaolin3303** [comment]
@fancyallen 我这边暂时没有微信小程序APP ID，不能在真机上看到效果，请贴一下你的机型和系统，这里做一下记录。
建议你这样尝试下看是否可以：
```
transform:scale(0.5);
-webkit-transform: scale(0.5);
```

**Comment by fancyallen** [comment]
@xiaolin3303  IOS 10.1.1   iphone6plus,   -webkit-transform试过啦，也没有作用，那就麻烦您先记录下拉啦，我再换别的手机试试

**Comment by xiaolin3303** [comment]
@fancyallen 我在真机上测试了下在不缩放的情况下是高清显示的（MAC IDE中是模糊的），所以我更新了代码，修改了高清显示的配置，请拉一下最新的代码，你的代码里就不要再用进行缩放了，请看一下你的手机上是不是OK的~
