### ISSUE TITLE
帮助文档

### ISSUE THREAD

**Issue by ohmycloud** [xiaolin3303/wx-charts#10]
js 小白完全不知道该怎么使用, 文档能否再详细点呢?

**Comment by xiaolin3303** [comment]
其实这个文档已经比较详细了，当然是关于`wx-charts`的使用文档，关于如何在微信小程序中使用起来，建议可以先看一下微信小程序的开发文档，如果哪儿衔接有问题的话可以在这里具体的把问题描述的出来
