### ISSUE TITLE
请问我怎么去掉数据拐点上的方块标识

### ISSUE THREAD

**Issue by renruijun** [xiaolin3303/wx-charts#100]
![qq 20170525155728](https://cloud.githubusercontent.com/assets/28946184/26441443/0534be8e-4163-11e7-8bd5-e81df4931e50.png)

**Comment by xiaolin3303** [comment]
`opts.dataPointShape Boolean default true` 是否在图表中显示数据点图形标识
[具体可以参看参数文档](https://github.com/xiaolin3303/wx-charts/issues/56)

**Comment by renruijun** [comment]
我昨天是有这样加上去这一条配置项，不过数据的方块标识图案并没消失，我加的方式不对吗？
![qq 20170526094212](https://cloud.githubusercontent.com/assets/28946184/26477402/0b73d8d0-41f8-11e7-800a-9d4f31692873.png)

**Comment by xiaolin3303** [comment]
参数没问题，你使用的`wx-charts`版本是不是比较早？

**Comment by renruijun** [comment]
我当初是下载的你的demo源码，版本是v1.0，我在哪里能获取到你的wxchart最新版本呢？

**Comment by xiaolin3303** [comment]
你`pull`下demo源码即可，里面已经更新了`wx-charts`

**Comment by renruijun** [comment]
嗯嗯，现在好了，可以了，谢谢啦！sixsixsix
![qq 20170526111212](https://cloud.githubusercontent.com/assets/28946184/26479232/4497b12a-4204-11e7-9d3f-08e88d6ee35f.png)

**Comment by EverChisato** [comment]
我现在也是这样子加，但是没有变化?我是刚刚下的demo，然后也替换掉刚下载的js文件了请问是什么问题呢？
![image](https://user-images.githubusercontent.com/25126812/30418219-dc18cb44-9964-11e7-9e09-068b056769ee.png)

**Comment by zengguoying** [comment]
请问areaChart中如何加竖线，绘制成网格形状？在线等！

**Comment by Joyce-guo** [comment]
请问我多条曲线，怎么设置转折处都是远点，而不是有的圆点，有的是方块呢，area能否加边界线border呢

**Comment by Chunianyou** [comment]
> 请问我多条曲线，怎么设置转折处都是远点，而不是有的圆点，有的是方块呢，area能否加边界线border呢

得到需求折线图上只显示圆点，没有找到配置置顶点形状的地方。修改源代码可以达到效果，如果大量页面需求不一样不推荐。

wxCharts源码：22行 dataPointShape: ['diamond', 'circle', 'triangle', 'rect'],  
修改为： dataPointShape: ['circle'],

如使用记得写好注释。
