### ISSUE TITLE
屏幕滚动问题

### ISSUE THREAD

**Issue by shengke90** [xiaolin3303/wx-charts#104]
您好，xiaolin3303！最近正好用用到，非常感谢！
手机屏一屏要显示好几个统计图，避免不了滑动屏幕，手指进入canvas热区后就滑动不了了（disable-scroll已设置为false），不知道是不是我使用的问题？
![2017-06-01 18 56 48](https://cloud.githubusercontent.com/assets/9584443/26676898/38bf5ee6-46fc-11e7-8733-2d610680367f.png)

**Comment by xiaolin3303** [comment]
这样设置试试 `disable-scroll=“{{false}}”` 或者 直接去掉`disable-scroll`属性，默认即为false

当时设置 `disable-scroll=“{{true}}”`可以参考这个[issue](https://github.com/xiaolin3303/wx-charts/issues/62)，目前来看微信小程序似乎修复了这个问题

**Comment by shengke90** [comment]
@xiaolin3303 按照您说的，完美解决！
