### ISSUE TITLE
canvas绘制的很模糊？

### ISSUE THREAD

**Issue by HeMi1995** [xiaolin3303/wx-charts#106]
![image](https://user-images.githubusercontent.com/9911800/26887583-f3766814-4bda-11e7-9880-d3269746a6cf.png)

**Comment by xiaolin3303** [comment]
真机还是模拟器？

**Comment by HeMi1995** [comment]
了解问题了，Mac 的屏幕是高清屏，canvas 绘制的都是模糊的，接普通外接显示器就OK 了

**Comment by weisterjie** [comment]
这个问题怎么解决呢

**Comment by zykaito** [comment]
@weisterjie 不需要解决，主要是 Mac 上的微信模拟器没有适配Mac pro 的高清视网膜屏幕，所以会模糊，一般手机就是普通的分辨率
