### ISSUE TITLE
直线数据data怎么动态调取

### ISSUE THREAD

**Issue by cui-xiao** [xiaolin3303/wx-charts#109]
![qq 20170613162125](https://user-images.githubusercontent.com/28530058/27072920-917b6bf4-5054-11e7-8014-95bdd7a49f3f.png)

**Comment by xiaolin3303** [comment]
获取数据的异步请求成功后在回调里面初始化`wxCharts`，把你的数据处理成wxCharts接收的形式传入配置即可
