### ISSUE TITLE
折线图大量数据的时候，会出现折行的情况，这个该怎么处理呢

### ISSUE THREAD

**Issue by lixijia** [xiaolin3303/wx-charts#11]
![1](https://cloud.githubusercontent.com/assets/12892436/21481390/0e2bf908-cba2-11e6-95b7-39c0dbf82d29.jpg)

**Comment by xiaolin3303** [comment]
`series`中的`data`长度需要和`categories`的长度对应

**Comment by lixijia** [comment]
已解决，谢谢



祝：
工作顺利！

李稀佳
玄谷信息技术南京有限公司
Add:南京市雨花台区花神路10号花神科技园1栋203室
Mobile：18625176211
Mail: xjia.li@topdeep.com
 
发件人： fang
发送时间： 2016-12-27 10:52
收件人： xiaolin3303/wx-charts
抄送： lixijia; Author
主题： Re: [xiaolin3303/wx-charts] 折线图大量数据的时候，会出现折行的情况，这个该怎么处理呢 (#11)
series中的data长度需要和categories的长度对应
