### ISSUE TITLE
height问题

### ISSUE THREAD

**Issue by lienmac** [xiaolin3303/wx-charts#112]
height:300px
![image](https://user-images.githubusercontent.com/6937495/27168403-10160c10-51d8-11e7-950d-7e38dc5ae3db.png)

height:200px;
![image](https://user-images.githubusercontent.com/6937495/27168424-2a6a2c40-51d8-11e7-8451-15d3bd74c910.png)

height:100px;
![image](https://user-images.githubusercontent.com/6937495/27168456-4f7e6410-51d8-11e7-9089-69d915ceb2ab.png)

代码如下：
![image](https://user-images.githubusercontent.com/6937495/27168487-72609bb0-51d8-11e7-993a-4754a9bb889e.png)
 深深感到这个height是柱型的高度而不是整个图标，是否可以修改下

**Comment by xiaolin3303** [comment]
微信小程序提供的canvas绘图是基于`px`而不是`rpx`, 故配置里面传入的`width`和`height`都是`px`为单位的，你的`wxss`里面定义的canvas高度所以也需要`px`为单位，和传入配置对应起来

**Comment by lienmac** [comment]
谢谢，样式中添加高度就可以了
