### ISSUE TITLE
touchHandler问题

### ISSUE THREAD

**Issue by shengke90** [xiaolin3303/wx-charts#114]
您好！touchHandler在真机上首次加载可以执行一次，后续再点击画布就不执行了，但在开发工具里是一直可以点击执行的，下面是两种情况的截图
![wechatimg18](https://user-images.githubusercontent.com/9584443/27376083-b0be48f6-56a3-11e7-80c4-b045b48925dc.jpeg)
![2017-06-21 16 57 37](https://user-images.githubusercontent.com/9584443/27375920-2a079d6c-56a3-11e7-8a94-92ec0d070cd6.png)
代码片段
![2017-06-21 17 03 32](https://user-images.githubusercontent.com/9584443/27376095-b7c5b7d8-56a3-11e7-8210-82a71304d7dc.png)

**Comment by xiaolin3303** [comment]
关于你的问题参考下这个[issue](https://github.com/xiaolin3303/wx-charts/issues/62)，另外你的微信版本是多少，上次我测试似乎这个问题已经修复了.

还有你可以更新下最新的代码，曲线绘制进行了优化，对一些情况下曲线可能出现在x轴下方的问题进行了修复

**Comment by shengke90** [comment]
@xiaolin3303 设备信息如下图，已经更新到最新版本了，在bindtouchstart中打印个东西真机上没有输出，开发工具上可以正常输出，我把前两个canvas的disable-scroll="{{true}}"时，首次进入小程序，canvas是可以正常点击，只要一点击后面disable-scroll="{{false}}" 的canvas，所有的canvas都不能正常执行touchHandler了，
![wechatimg19](https://user-images.githubusercontent.com/9584443/27421403-cf8abc38-575c-11e7-8cc4-7f38d33a8968.jpeg)

**Comment by xiaolin3303** [comment]
那应该是还没有修复，具体参见#62
