### ISSUE TITLE
新版本出错，不能导入！

### ISSUE THREAD

**Issue by czflike** [xiaolin3303/wx-charts#117]
1月份的wxcharts.js没问题，为何新的wxcharts.js不能运行？

错误提示如下：
WAService.js:8 Uncaught Error: module "utils/wxcharts.js" is not defined

VM141:2 wxcharts.js
SyntaxError: unknown: Unexpected token (7:0)
   5 | 
   6 | 
>  7 | <!DOCTYPE html>
     | ^
   8 | <html lang="en">
   9 |   <head>
  10 |     <meta charset="utf-8">

**Comment by xiaolin3303** [comment]
请提供下具体的报错信息以便排查
