### ISSUE TITLE
能不能实现点击坐标，显示点的内容呢？

### ISSUE THREAD

**Issue by lixijia** [xiaolin3303/wx-charts#12]

**Comment by xiaolin3303** [comment]
暂不支持此功能，后续可能会添加，请保持关注

**Comment by lixijia** [comment]
请问，如果我们想不在线上显示点，该怎么处理呢



祝：
工作顺利！

李稀佳
玄谷信息技术南京有限公司
Add:南京市雨花台区花神路10号花神科技园1栋203室
Mobile：18625176211
Mail: xjia.li@topdeep.com
 
发件人： fang
发送时间： 2016-12-28 10:57
收件人： xiaolin3303/wx-charts
抄送： lixijia; Author
主题： Re: [xiaolin3303/wx-charts] 能不能实现点击坐标，显示点的内容呢？ (#12)
Closed #12.

**Comment by xiaolin3303** [comment]
![image](https://cloud.githubusercontent.com/assets/8075923/21637054/2d2dade2-d2a0-11e6-89e4-8eee31ceae02.png)


你说的是这个点吗？

**Comment by lixijia** [comment]
是的



祝：
工作顺利！

李稀佳
玄谷信息技术南京有限公司
Add:南京市雨花台区花神路10号花神科技园1栋203室
Mobile：18625176211
Mail: xjia.li@topdeep.com
 
发件人： fang
发送时间： 2017-01-04 17:07
收件人： xiaolin3303/wx-charts
抄送： lixijia; Author
主题： Re: [xiaolin3303/wx-charts] 能不能实现点击坐标，显示点的内容呢？ (#12)
你说的是这个点吗？

**Comment by lixijia** [comment]
对，就是那个点



祝：
工作顺利！

李稀佳
玄谷信息技术南京有限公司
Add:南京市雨花台区花神路10号花神科技园1栋203室
Mobile：18625176211
Mail: xjia.li@topdeep.com
 
发件人： fang
发送时间： 2017-01-04 17:07
收件人： xiaolin3303/wx-charts
抄送： lixijia; Author
主题： Re: [xiaolin3303/wx-charts] 能不能实现点击坐标，显示点的内容呢？ (#12)
你说的是这个点吗？

**Comment by xiaolin3303** [comment]
配置里增加了 `dataPointShape`

如下设置即可不显示数据点图形标识
```javascript
dataPointShape: false
```

**Comment by lixijia** [comment]
这个是新版本，还是老版本的呀




祝：
工作顺利！

李稀佳
玄谷信息技术南京有限公司
Add:南京市雨花台区花神路10号花神科技园1栋203室
Mobile：18625176211
Mail: xjia.li@topdeep.com
 
发件人： fang
发送时间： 2017-01-05 09:42
收件人： xiaolin3303/wx-charts
抄送： lixijia; Author
主题： Re: [xiaolin3303/wx-charts] 能不能实现点击坐标，显示点的内容呢？ (#12)
配置里增加了 dataPointShape
如下设置即可不显示数据点图形标识
dataPointShape: false
