### ISSUE TITLE
建议还是写个 API 文档吧

### ISSUE THREAD

**Issue by icarusion** [xiaolin3303/wx-charts#124]
东西还不错，至少在 GitHub 上找不出更好的了。但现在 API 基本靠猜啊，比如隐藏图例，修改图片颜色什么的。
另外，Tooltip 还是希望可以 format 内容。

**Comment by xiaolin3303** [comment]
有专门的api文档，readme里面有链接，注意看下   #56  #57

**Comment by icarusion** [comment]
OK, thx

**Comment by hgq520** [comment]
没有api文档，不知道该怎么用啊
