### ISSUE TITLE
showToolTip 能否显示对应的x轴数据

### ISSUE THREAD

**Issue by yuyang1004** [xiaolin3303/wx-charts#126]
showToolTip 能否显示对应的x轴数据
如: x轴为日期,是否可以在showToolTip 的时候把日期显示在showToolTip 内

**Comment by guaicaiboshi** [comment]
其实这个很简单，自己扩展下就好了
if (index > -1) {
      var categoriesData =this.opts.categories[index];//这里增加
      var seriesData = getSeriesDataItem(this.opts.series, index);

然后是   var _getToolTipData = getToolTipData2(categoriesData,seriesData, this.chartData.calPoints, index),
我扩展了个getToolTipData2，具体代码：
function getToolTipData2(categoriesData, seriesData, calPoints, index) {
  var textList = seriesData.map(function (item) {
    return {
      text: categoriesData + ': '+ item.data,
      color: item.color
    };
  });
  var validCalPoints = [];
  var offset = {
    x: 0,
    y: 0
  };
  calPoints.forEach(function (points) {
    if (typeof points[index] !== 'undefinded' && points[index] !== null) {
      validCalPoints.push(points[index]);
    }
  });
  validCalPoints.forEach(function (item) {
    offset.x = Math.round(item.x);
    offset.y += item.y;
  });

  offset.y /= validCalPoints.length;
  return { textList: textList, offset: offset };
}

这样就OK 了

**Comment by cnvp** [comment]
这是在哪里加的？找不到位置啊

**Comment by xiaolin3303** [comment]
#147

**Comment by darrenDenghongjiu** [comment]
var process = arguments.length > 4 && arguments[4] !== undefined ? arguments[4] : 1;

    var pieOption = opts.extra.pie || {};
    series = getPieDataPoints(series, process);
    var centerPosition = {
		//配置说明:(opts.width / 2)宽度的一半为圆的left开始位置 想要居中需要left = width/2 + 浏览器的宽度-canvas画得圆的宽度/2(等于剩余宽度得一半)
		//即left得开始位置(opts.width / 2)+((opts.countWidth-opts.width)/2)
		//使用说明：countWidth = 浏览器宽度
        x: (opts.width / 2)+((opts.countWidth-opts.width)/2),
        y: (opts.height - config.legendHeight) / 2
    };
