### ISSUE TITLE
当type为column时，数据存在负数，显示不正常

### ISSUE THREAD

**Issue by jianzi0307** [xiaolin3303/wx-charts#128]
![image](https://user-images.githubusercontent.com/2997173/28239300-e1b11df2-699b-11e7-8e94-3939e95b981a.png)

图示数据为：
`[0, 0, -0.2, 0, -10, -3, 0]`

**Comment by xiaolin3303** [comment]
柱状图目前不支持负数的数据，后续会跟进，保持关注
