### ISSUE TITLE
折线图，当把线条设置为曲线时，两个相邻点为0时会出现这种情况，很别扭，建议这种情况直接连直线

### ISSUE THREAD

**Issue by jianzi0307** [xiaolin3303/wx-charts#129]
![image](https://user-images.githubusercontent.com/2997173/28241219-e18afa24-69c2-11e7-815c-d92b6816a270.png)

如图所示

**Comment by fhqrnr** [comment]
我也是一样的问题，看来我问题提重复了

**Comment by xiaolin3303** [comment]
之前修复过了，拉一下最新的代码
