### ISSUE TITLE
请问插件在开发工具，ios画图正常，安卓画图空白，从哪里入手解决

### ISSUE THREAD

**Issue by chenym1992** [xiaolin3303/wx-charts#13]
求解！3q @xiaolin3303

**Comment by xiaolin3303** [comment]
安卓上我测试过一个机子，没有问题，你的安卓是什么系统？ 有没有系统报错信息，具体贴一下

**Comment by chenym1992** [comment]
三星 4.4.2  微信 6.3.32测试版  没报错

**Comment by xiaolin3303** [comment]
我这边暂时没有这款机型，这样，初始化的时候你把new Charts()写在全局Page({})外部试试，看看是否有系统报错提示

**Comment by chenym1992** [comment]
我试试

**Comment by chenym1992** [comment]
没报错，但是图还是没有

**Comment by chenym1992** [comment]
但是有警告：On PageReady can not find 1133943864 ,App service not ready

**Comment by xiaolin3303** [comment]
我这边暂时没有这种机型，看系统的话`Android 4.4.2`是有点低了，有机会了找个这机子测一下，你先试试其他版本高一点的Android系统吧

**Comment by chenym1992** [comment]
en
