### ISSUE TITLE
折线图无法使页面滑动

### ISSUE THREAD

**Issue by guaicaiboshi** [xiaolin3303/wx-charts#133]
如果折线图的demo wxml界面修改为
`<view class="container">
  <view class="" style="height:800px"></view>
    <canvas canvas-id="lineCanvas" disable-scroll="true" class="canvas" bindtouchstart="touchHandler"></canvas> 
  <button type="primary" bindtap="updateData">更新数据</button>
</view>`

那当滑动到底部看到图片，然后点击图片向上滑动的时候，发现是不起作用的。请问如何解决

**Comment by guaicaiboshi** [comment]
以解决

**Comment by yhuaqiang** [comment]
请问滑动问题怎么解决的

**Comment by guaicaiboshi** [comment]
设置 disable-scroll="{{false}}"   和解决问题！如有其他问题，周一帮你解决

**Comment by xiaolin3303** [comment]
当时添加disable-scroll="{{true}}"的原因请参考 #62
