### ISSUE TITLE
line曲线图在真机iPhone6 plus上showToolTip不显示

### ISSUE THREAD

**Issue by 1181888200** [xiaolin3303/wx-charts#137]
`  touchHandler: function (e) {
      console.log(lineChart.getCurrentDataIndex(e));
      lineChart.showToolTip(e, {
          background: '#7cb5ec'
      });
  },`
iPhone6 plus 机器上测试
在真机上这个地方的lineChart.getCurrentDataIndex(e)值永远是第一次点击的值。以后不再变动

而在安卓机器上却是可以显示的

**Comment by xiaolin3303** [comment]
参考下 #73
