### ISSUE TITLE
绘制的line弧度弯到了负值区域

### ISSUE THREAD

**Issue by fhqrnr** [xiaolin3303/wx-charts#139]
![image](https://user-images.githubusercontent.com/5975504/28718968-c0747c4e-73da-11e7-8fa2-67c6d3f89a14.png)

**Comment by xiaolin3303** [comment]
请确保使用了最新的代码版本

**Comment by fhqrnr** [comment]
已使用了最新的代码版本，确认还存在

**Comment by xiaolin3303** [comment]
@fhqrnr  贴一下你的配置 主要是数据

**Comment by fhqrnr** [comment]
var cacheData = {"hour":["00:00","01:00","02:00","03:00","04:00","05:00","06:00","07:00","08:00","09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00"],"finished":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,88,151,134,159,50,0,0,0],"finishedTotal":582,"receive":[131,3,1,0,0,0,0,3,7,28,46,58,36,48,43,53,60,51,15,0,0,0],"receivedTotal":583}

lineChart = new wxCharts({
  canvasId: 'lineCanvas',
  type: 'line',
  categories: cacheData.hour,
  animation: true,
  background: '#f5f5f5',
  series: [{
    name: '接收量',
    data: cacheData.receive,
  }, {
    name: '完成量',
    data: cacheData.finished,
  }],
  xAxis: {
    disableGrid: true,
    gridColor:'#E9E9E9',
  },
  yAxis: {
    gridColor:'#E9E9E9',
    min: 0
  },
  width: windowWidth,
  height: 300,
  dataLabel: false,
  dataPointShape: true,
  extra: {lineStyle: 'curve'}
})

**Comment by joweyoung** [comment]
同问，一样出现了这个问题
