### ISSUE TITLE
当x轴坐标太多时，是否能够自动适应刻度分配

### ISSUE THREAD

**Issue by shunzizhan** [xiaolin3303/wx-charts#14]
背景:当返回的数据很多时，x轴的刻度很密集，不知是否支持自动适配，如果间隔很小，则x周刻度可取几个为一组，类似百度的echart
![image](https://cloud.githubusercontent.com/assets/7811369/21540064/7a266890-cde7-11e6-9ce9-65f9e27dd100.png)
百度e'char图
![image](https://cloud.githubusercontent.com/assets/7811369/21540079/a5f36de2-cde7-11e6-93ee-e03f4945fa59.png)

**Comment by xiaolin3303** [comment]
做了一下X轴文案碰撞的避让，效果类似这样，拉一下最新的代码
<img width="354" alt="2016-12-30 12 49 30" src="https://cloud.githubusercontent.com/assets/8075923/21560235/c9aba52e-ce96-11e6-822a-6cb243c9740c.png">

x轴分组的问题后续会开发，请保持关注

**Comment by shunzizhan** [comment]
不知是那个属性来控制这个旋转角度，readme文档貌似没有同步更新

**Comment by xiaolin3303** [comment]
官方文档的[API](https://mp.weixin.qq.com/debug/wxadoc/dev/api/canvas/rotate.html?t=20161229)

只能旋转整个画布来进行控制

**Comment by shunzizhan** [comment]
也就是说，你现在是不管x轴数据刻度是多少，刻度都是斜置？

**Comment by xiaolin3303** [comment]
如果X轴内容放置不下才会倾斜显示来避让，否则还是之前的样式，你可以自己试一下

**Comment by shunzizhan** [comment]
好的

**Comment by bianjiang998** [comment]
如果数据有几百条怎么办，数据太多时线条也会显示模糊，求解啊

**Comment by xiaolin3303** [comment]
数据太多建议把数据自行抽稀或者数据分段分图表显示
