### ISSUE TITLE
和swiper组件冲突

### ISSUE THREAD

**Issue by liuyon7** [xiaolin3303/wx-charts#141]
这个和swiper组件一起使用的时候, 绘画出的canvas图像 不随屏幕滑动一起移动,就感觉像是被固定定位了, 请问你们有遇到这个问题吗? (在微信开发者工具里 是正常的 但是手机上就会出现这个问题, 安卓,IOS 都有这个问题.)

**Comment by xiaolin3303** [comment]
参看小程序官方文档`canvas`部分

>Bug & Tip
>
>tip: canvas 组件是由客户端创建的原生组件，它的层级是最高的。
>tip: 请勿在 scroll-view 中使用 canvas 组件。
>tip: css 动画对 canvas 组件无效。

**Comment by giserman001** [comment]
谢谢

**Comment by txw8** [comment]
谢谢!

**Comment by namezy** [comment]
disable-scroll="true" 滚动的scrollLine 页面不能上下正常滚动，开发工具可以，手机不可以。
