### ISSUE TITLE
请问怎么在showToolTip上也可以显示x轴的数据？

### ISSUE THREAD

**Issue by cnvp** [xiaolin3303/wx-charts#147]

**Comment by xiaolin3303** [comment]
添加了toopTip自定义内容显示，具体参看文档或者[wx-charts-demo](https://github.com/xiaolin3303/wx-charts-demo)`line`图的配置

**Comment by cnvp** [comment]
抽稀的同时 showtooltip上显示x轴和y轴的数据




------------------ 原始邮件 ------------------
发件人: "fang";<notifications@github.com>;
发送时间: 2017年8月16日(星期三) 晚上9:10
收件人: "xiaolin3303/wx-charts"<wx-charts@noreply.github.com>; 
抄送: "万希"<183784945@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xiaolin3303/wx-charts] 请问怎么在showToolTip上也可以显示x轴的数据？ (#147)




添加了toopTip自定义内容显示，具体参看文档或者wx-charts-demoline图的配置

**Comment by cnvp** [comment]
现在是自动轴稀的，可以showToolTip上可以同时显示x轴和y轴的数据，能否再次抽稀？因为我看着感觉还是很密集，

**Comment by cnvp** [comment]
@xiaolin3303 x轴目前看着很密集，[http://www.wxcnvp.cn/wxcnvp/charts.png](url)，能否x轴再次抽稀，并且数据点直接的能否用线链接起来，我用的是area类型，望解答，感谢
