### ISSUE TITLE
曲线图中的series.data参数应该允许输入一个数组对象

### ISSUE THREAD

**Issue by henlyyang** [xiaolin3303/wx-charts#153]
曲线图中的series.data参数应该允许输入一个数组对象，然后通过series.value这个参数让用户定义从一个对象中取得数字值的functon，series.format参数不变，不过它可以接收两个参数输入，一个是当前对象，一个是当前对象所在的下标。代码如下：
series: [{
        name: '成交量1',
        data: [{v:1,t:'aaa'}, {v:2,t:'bbb'}, {v:3,t:'cccc'}],
        value:function(val){
            return val.v;
         },
        format: function (val, index) {
            return val.v.toFixed(2) + val.t + index;
       }
    }

这样修改的好处是：接收的数据可以是对象（因为很多API返回的数据都是一个对象列表），而且数据格式化显示那里可以更加灵活和方便

**Comment by xiaolin3303** [comment]
这个变动比较大，所以暂时不考虑支持，建议先做一次数据处理。
