### ISSUE TITLE
如果使用标签横向滚动，图的宽度可以调整成整个scroll-view的宽度吗？100%没有包括横向滚动的宽度

### ISSUE THREAD

**Issue by LongYue9608** [xiaolin3303/wx-charts#155]
我想绘制类似墨迹天气小程序的气温曲线图

**Comment by xiaolin3303** [comment]
宽度的话需要自行计算成整个的宽度

注意下官网的信息：
Bug & Tip

tip: canvas 组件是由客户端创建的原生组件，它的层级是最高的。
tip: 请勿在 scroll-view 中使用 canvas 组件。
tip: css 动画对 canvas 组件无效。

**Comment by LongYue9608** [comment]
有什么办法让图可以左右滑动吗？我给canvas的宽度设置了1020rpx;实际显示的依然是一个屏幕的宽度，固定的

**Comment by LongYue9608** [comment]
另外，我设置了  yAxis: {disabled :true, },xAxis : { disableGrid:false, disabled: true,//后面这个属性好像没有},x轴依然会出现

**Comment by niannian311** [comment]
同求，请问wx_charts能够实现左右拖拽图表，实现图表内容左右滑动显示吗？

**Comment by LongYue9608** [comment]
别问这个问题了，微信文档明确的写了别在scroll里面用canvas,另外，折现图我用Java实现了我想要达到的效果。

**Comment by riversword** [comment]
@LongYue9608 我也想要实现一个可以左右滑动的曲线图，跟 墨迹天气小程序的气温曲线图一样，网上找半天都没有解决办法。。。你的办法是什么思路呀

**Comment by LongYue9608** [comment]
@riversword 你是指如何生成折线图的问题，还是说图片左右滑动的问题

**Comment by riversword** [comment]
@LongYue9608  让canvas跟随<view>一起左右滑动

**Comment by riversword** [comment]
@LongYue9608 让canvas跟随外层的view一起左右滑动

**Comment by LongYue9608** [comment]
@riversword 好像是转成图片

**Comment by niannian311** [comment]
@riversword 作者已经更新了这个插件，新版的插件已经支持生成左右滑动的折线图或者柱状图了，你直接调这个插件里的方法就行了。
