### ISSUE TITLE
iphone 6上面报错TypeError: undefined is not an object(evaluating ‘a.length’ ) ，android机正常

### ISSUE THREAD

**Issue by qucc** [xiaolin3303/wx-charts#163]
TypeError: undefined is not an object(evaluating ‘a.length’ ) at formatChartData function ;at setTimeout callback function 
这是我调用的方式
formatChartData: function (data) {
    var series = [];
    for (var i in data.Rows) {
      var row = data.Rows[i];
      series.push({
        name: row[data.LegendBy],
        data: row.Data
      });
    }
    return series;
  }

**Comment by xiaolin3303** [comment]
请把你的`series`最终的数据打印一下贴出来

**Comment by qucc** [comment]
嗯，找到原因了，是数据的问题。 ios不支持 ‘2017-10-14 ： 10:10:00’ 这样的时间格式，换成'2017/10/14 ： 10:10:00' 或ISO 8601时间格式就成功了。
