### ISSUE TITLE
如何让x轴从零开始绘制? 以及背景色渐变呢?

### ISSUE THREAD

**Issue by Marcusias** [xiaolin3303/wx-charts#164]
![2017-09-11 5 56 25](https://user-images.githubusercontent.com/13980779/30269166-8b5fb754-971a-11e7-9458-428942d3b45c.png)

**Comment by xiaolin3303** [comment]
目前不支持渐变色，x轴从零开始绘制指的是Y轴的刻度从0开始吗？

**Comment by Marcusias** [comment]
通过修改  均已实现~~~
