### ISSUE TITLE
折线图数据量很大的时候无法自适应

### ISSUE THREAD

**Issue by ZxBing0066** [xiaolin3303/wx-charts#18]
![image](https://cloud.githubusercontent.com/assets/5652404/21801994/064cde00-d75f-11e6-9a82-352857511938.png)
![image](https://cloud.githubusercontent.com/assets/5652404/21802000/0ddce458-d75f-11e6-8537-02fd11649746.png)

当折线图数据很多的时候完全乱了，不知能否实现自动过滤出几个category来显示，然后加了min=0不知道为什么不生效。

**Comment by xiaolin3303** [comment]
第一个问题已经修复，拉一下最新的代码

关于第二问题设置`min`不生效，是因为你的所有数据值应该都是0，如果你设置`min`为0的话，那么数据点的最大值和最小值(`min`)同样也是0，在最大值最小值相等的情况下工具默认会把数据居中处理

**Comment by xiaolin3303** [comment]
在存在X轴数据过多的情况，建议配置
```
xAxis: {
    disableGrid: true
}
```

效果比如这样的：
![image](https://cloud.githubusercontent.com/assets/8075923/21803232/232ad50e-d764-11e6-881c-4171c7de6e14.png)

**Comment by ZxBing0066** [comment]
🙏 厉害了word哥，神速简直了。
不过稍微有点小问题就是X轴文本比较长的时候会超出canvas

**Comment by xiaolin3303** [comment]
x轴文案还是尽量控制短一点，太长程序不太好控制

**Comment by xiaolin3303** [comment]
新增了Y轴最大值配置，对应你的情况可以这样配置

```javascript
yAxis: {
    ...
    max: 1
}
```

![image](https://cloud.githubusercontent.com/assets/8075923/21831928/7e354a46-d7e2-11e6-9f71-d38fb5acc08a.png)

**Comment by ZxBing0066** [comment]
好的 🙏   太感谢了
