### ISSUE TITLE
关于本地缓存数据的格式化问题

### ISSUE THREAD

**Issue by zsenliao** [xiaolin3303/wx-charts#180]
首先非常感谢，在一个项目中用到了 `wx-charts`。

在项目中遇到过一个情况，就是展示趋势数据。因为趋势数据不包括当前的，为了减少接口的请求次数，采用了本地缓存的方式。但目前似乎 原始数据中增加了 `format:function(){}` 之后，小程序缓存之后的取值并不会带上这个。这样就导致原始数据与缓存数据，在渲染之后的显示上并不一致。

我的做法是，在构造时增加了一个 `formatData` 参数，并传值到 `drawPointText` 函数内，然后调整了一下 `var formatVal = series.format ? series.format(data[index]) : (fmt ? fmt(data[index]) : data[index]);` 

不过这种方式只能做同一个格式化，不能针对不同的数据做区别性的格式化。或者有更好的方式？

**Comment by xiaolin3303** [comment]
缓存的应该仅限于你的数据，format属于数据的格式化方法，不应该缓存起来，你可以取到数据后再通过一个类似的工厂函数把数据进行处理，比如加上`format`等，当然你可能要对数据进行多种format操作，
一种建议是：
你可以先定义好各项操作
```
{
    doSomeFormat: function () { ... },
    doAnotherFormat: function () { ... },
    ....
}
```
存储数据的时候format存对应的key, 取出数据的时候做一次处理对应到具体的函数

**Comment by zsenliao** [comment]
当时确实没有想到你说的此方案。
不过因为我的需求目前不需要对不同的数据做单独显示处理，因此暂时没有按照你说的去实现。😄
