### ISSUE TITLE
iPhone7 ios10.0 手机端预览无内容

### ISSUE THREAD

**Issue by Shawyau** [xiaolin3303/wx-charts#2]
copy的您的代码，重新创建了一个新的小程序，开发者工具中有图表内容。当初始化new Charts()写在全局Page({})外部时，手机端预览会直接弹出一个serviceScript error的提示，无图表内容；当把new Charts()写在页面onLoad或者onReady函数里的时候手机端预览无弹窗提示，也无内容

**Comment by Shawyau** [comment]
顺便贴下弹出的错误截图
![img_0306](https://cloud.githubusercontent.com/assets/19165200/20961163/cd566c7c-bc9e-11e6-9212-3832636a872e.PNG)

**Comment by xiaolin3303** [comment]
看报错应该是iPhone7 ios10.0中不支持`requestAnimationFrame`，做了一下兼容，请拉一下最新的代码。也请你帮我测试一下这个机型
