### ISSUE TITLE
Bug 背景设置为黑色后右边有一个12像素的白条

### ISSUE THREAD

**Issue by Zhao-666** [xiaolin3303/wx-charts#203]
![image](https://user-images.githubusercontent.com/25931337/33697887-38db4778-db44-11e7-9902-4360eb940730.png)
![image](https://user-images.githubusercontent.com/25931337/33697904-4f542326-db44-11e7-92dd-10ed03e14419.png)

**Comment by Zhao-666** [comment]
设置opt.background为背景颜色后解决

**Comment by oldtom99** [comment]
我也遇到了这个情况，但是我的页面背景色为渐变色，这种应该怎么解决
