### ISSUE TITLE
设置了Y轴的min之后传入数据全部为0时，min值无效

### ISSUE THREAD

**Issue by Zhao-666** [xiaolin3303/wx-charts#204]
![image](https://user-images.githubusercontent.com/25931337/33753513-a6125140-dc22-11e7-8e55-58607e7e1c63.png)

**Comment by YouRNotPaulChan** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by YouRNotPaulChan** [comment]
查看了wecharts.js文件之后发现了getYAxisTextList方法中有对这个地方进行了处理，但是设置了之后发现图表的顶端出现了一些字符

**Comment by YouRNotPaulChan** [comment]
刚发现顺手解决了 @Zhao-666 
![image](https://user-images.githubusercontent.com/26828477/35151054-c4cb3448-fd57-11e7-9804-d39e3d2e7159.png)

**Comment by Zhao-666** [comment]
@YouRNotPaulChan 感谢~~

**Comment by zjsyxrf** [comment]
直接设置max: 1就可以了

**Comment by er567** [comment]
min:1 ，max: 5
