### ISSUE TITLE
传入数值全为0时 显示有问题

### ISSUE THREAD

**Issue by lllsss** [xiaolin3303/wx-charts#21]
你好，我在给饼图传入全0数值后，饼图不会显示，同时，同一页面带有点击事件的view，点击事件不会触发。
我尝试在数值全为0的情况将canvas的容器view设置display: none;还是不能点击。
(全0的情况在后台是确实存在的)
请问该怎么解决，谢谢。

**Comment by xiaolin3303** [comment]
同一页面带有点击事件的view和canvas是什么关系？嵌套？

**Comment by lllsss** [comment]
同一页面带有点击事件的view和canvas的容器view是同级的

**Comment by xiaolin3303** [comment]
你描述的情况已经超出了本工具讨论的范围，如果数据都是0饼图确实没有办法显示，点击事件没生效请看一下是否是数据都是0的情况时页面的其他逻辑是否有报错造成的影响，good luck

**Comment by lllsss** [comment]
嗯，我再去查下看看，谢谢。

**Comment by xiaolin3303** [comment]
我尝试了你的步骤，确实存在此情况，也没有出现报错情况，可能是微信小程序的一个bug，推荐你这样做，绘制饼图的时候如果数据全为0（这个你可以判断出来）就不要执行
```javascript
new wxCharts()
```
同时隐藏`canvas`

good luck~

**Comment by lllsss** [comment]
不执行new然后隐藏掉canvas就好了。
我之前隐藏的是canvas的容器view。
谢谢。
