### ISSUE TITLE
Pie图的 dataLabel 能否显示除百分比外数据本身的数值？

### ISSUE THREAD

**Issue by green-dalii** [xiaolin3303/wx-charts#211]
使用 Pie 图时，设置`dataLabel:true`只能显示百分比，我想显示原始数据的数值，如何操作？

**Comment by green-dalii** [comment]
已解决，查阅 #56 中数据列表定义： 

> dateItem.format Function 自定义显示数据内容

通过以下方式定义 `format` ，return回 `this.data`便可实现显示原始数据数值：
```
format: function () {
    return this.data;
}
```

**Comment by AmoSunsh1ne** [comment]
具体应该怎么写呢，我照着该怎么不对呢

**Comment by voidmain90** [comment]
可以再饼图下面的名称上进行显示 
pieChart = new wxCharts({
            animation: true,
            canvasId: 'pieCanvas',
            type: 'pie',
            series: [{
                name: '正常 : '+this.data.normal+'台' ,
                data: this.data.normal,
                color:'rgb(116, 240, 59)',
                
            }, {
                name: '离线 : '+this.data.offline+'台',
                data: this.data.offline,
                color:'orange'
            }, {
                name: '角度偏差 : '+this.data.angleerror+'台',
                data: this.data.angleerror,
                color:'rgb(243, 103, 103)'
            }],
            width: windowWidth,
            height: 300,
            dataLabel: true,
            animation:true,           
        });

**Comment by voidmain90** [comment]
具体数值可以通过下面的文字进行显示 ,希望对您有所帮助
pieChart = new wxCharts({
            animation: true,
            canvasId: 'pieCanvas',
            type: 'pie',
            series: [{
                name: **'正常 : '+this.data.normal+'台'** ,
                data: this.data.normal,
                color:'rgb(116, 240, 59)',
                
            }, {
                **name: '离线 : '+this.data.offline+'台'**,
                data: this.data.offline,
                color:'orange'
            }],
            width: windowWidth,
            height: 300,
            dataLabel: true,
            animation:true,
            format: function () {
              return this.data;
          }
        });
