### ISSUE TITLE
线形图表X轴显示问题

### ISSUE THREAD

**Issue by mengzhimin2011** [xiaolin3303/wx-charts#22]
线形图标中，如果数据过多，会导致X轴太过密集无法正常显示，甚至导致数据显示不全，请问有办法让数据正常显示，但是X轴biaozhu标注不出现呢？如图：可以去掉下面的日期不显示。正常显示数据吗？
![image](https://cloud.githubusercontent.com/assets/25052958/21842525/2a610ba4-d822-11e6-9663-ff09626da02a.png)

**Comment by xiaolin3303** [comment]
参看 #18

**Comment by mengzhimin2011** [comment]
配置的时候已经配置了
  xAxis: {
    disableGrid: true
}
但是没用，我的数据在上千个。有办法不显示X轴标注吗？或者X轴是一个区间

**Comment by xiaolin3303** [comment]
@mengzhimin2011 确保你更新了最新版本的代码，X轴现在不会出文案现重叠的情况
如果要加上隐藏X轴的配置会觉得很怪，如果没有X轴应该不叫图表工具，叫折线图了

当然针对你的情况：
如果你的数据有上千个，最好你要做一下分类，不要全部一下交给图表工具来处理，根据不同的条件动态的调用（可以针对同一个canvas多次调用）
```javascript
new wxCharts()
```

**Comment by xiaolin3303** [comment]
如果你有强烈的需求不显示X轴，可以这样配置
```javascript
categories: ['', '', '', ...],
xAxis: {
    disableGrid: true
}
```
