### ISSUE TITLE
配色问题

### ISSUE THREAD

**Issue by Bleoo** [xiaolin3303/wx-charts#25]
所有文字颜色 以及表格栅栏的颜色 能不能传参 自定义

**Comment by Bleoo** [comment]
我自己到JS去改了一点点，不知道怎么实现传参配色 以及文字的显隐

**Comment by xiaolin3303** [comment]
配色配置正在开发，`文字的显隐`具体指什么？

**Comment by Bleoo** [comment]
![p0l xik5e u32 92c3 z2f](https://cloud.githubusercontent.com/assets/11569795/22007647/5826c7c2-dcaf-11e6-9161-ff04cc42d71c.png)
这几个区域的文字配色，以及文字配色
我这里开发不需要左边文字的显示，所以想传参隐藏

**Comment by xiaolin3303** [comment]
你说所的文案的隐藏现在都是支持的，可以仔细阅读以下`README`

比如隐藏Y轴`title`
不设置`opts.yAxis.title`即可

**Comment by xiaolin3303** [comment]
增加了配色设置，具体请看`README`
