### ISSUE TITLE
折线图Y轴min起始值无效

### ISSUE THREAD

**Issue by Bleoo** [xiaolin3303/wx-charts#26]
![1484632452 1](https://cloud.githubusercontent.com/assets/11569795/22009228/89dd22cc-dcbc-11e6-8c45-27c1281d6359.jpg)
```java
yAxis: {
        min: 100,
        max: 160
      }
```

**Comment by xiaolin3303** [comment]
如果你数据的最小值小于`yAxis.min`，会忽略`yAxis.min`，`yAxis.max`同理
