### ISSUE TITLE
在当前页面添加遮罩层，canvas一直处于置顶状态。

### ISSUE THREAD

**Issue by xiechunwei** [xiaolin3303/wx-charts#266]

**Comment by LucyLiuluxi** [comment]
@xiechunwei 使用cover-view代替遮罩层的view

**Comment by xiechunwei** [comment]
但cover-view不能满足我的需求，cover-view不能添加其他组件，用了简单粗暴的方法，弹窗的时候直接隐藏canvas.



敬祝：工作顺利  生活开心
------------------------------
谢春为
E-mail：xiechunwei@pcw268.com
Cel：13162865356

上海晓财科技有限公司
Web：http://www.pcw365.com
Tel：400-600-2063
Add：上海市徐汇区桂平路418号国际孵化中心A区403室
 
发件人： LucyLiuluxi
发送时间： 2018-05-22 17:17
收件人： xiaolin3303/wx-charts
抄送： xiechunwei; Mention
主题： Re: [xiaolin3303/wx-charts] 在当前页面添加遮罩层，canvas一直处于置顶状态。 (#266)
@xiechunwei 使用cover-view代替遮罩层的view
