### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by longzc1314** [xiaolin3303/wx-charts#27]
纯小白来着  应该怎么引用这个js呢 是不是在.wxml里面要申明申明 应该怎么申明

**Comment by xiaolin3303** [comment]
请参看 #28

**Comment by exo-m** [comment]
请问一下，我这边有两个数据，数值分别是0.04和45345.01，环状图就绘制不出来了。。。这是bug么

**Comment by xiaolin3303** [comment]
@exo-m 贴一下你的配置和截图

**Comment by celesteLee** [comment]
我用手机测试的时候，拉动屏幕时这个图表会上下抖动？？？而且显示不全？在开发工具显示都正常？？为什么呢？
