### ISSUE TITLE
wx-charts会和所在页面的弹层重叠显示

### ISSUE THREAD

**Issue by GitOffice** [xiaolin3303/wx-charts#271]
@xiaolin3303  在电脑的调试工具里没重叠 ，只在所有手机上出现过。请解答，谢谢！
![11](https://user-images.githubusercontent.com/1814649/41230124-321ee5ac-6db1-11e8-9a7a-d76169188181.jpg)

**Comment by dzahao** [comment]
我也出现这个问题，canvas层级要比弹出层还要高，甚至在调试模式下的弹窗也会影响。
