### ISSUE TITLE
你好，请问line粗细可以设置吗？

### ISSUE THREAD

**Issue by Bluergao** [xiaolin3303/wx-charts#273]
如题

**Comment by Chunianyou** [comment]
![image](https://user-images.githubusercontent.com/38035696/55786015-02f37b80-5ae6-11e9-845a-6079d2cab616.png)
同样需求改变折线的粗细，在源码中设置的，方法和修改位置已框选。仅供页面/项目显示相同粗细的折线图或者只有一个折线图的情况。

**Comment by Bluergao** [comment]
ths！
