### ISSUE TITLE
如何正确使用这个

### ISSUE THREAD

**Issue by longzc1314** [xiaolin3303/wx-charts#29]
.wxss文件中这样写的
 <canvas canvas-id="pieCanvas" style="border: 1px solid;"/>
.js中
var wxCharts = require('./utils/wxcharts.js');
Page({
    ...
    onLoad: function() {
        new wxCharts({
            ...
        });
    }
});
这样写的就看到canvas的图框 里面没显示其他的内容

**Comment by xiaolin3303** [comment]
@longzc1314 具体请查看 #28
