### ISSUE TITLE
wx-charts适配问题

### ISSUE THREAD

**Issue by sider666** [xiaolin3303/wx-charts#3]
我做出pie图后  我在iphone6 和iphone5的尺寸下 位置显示不统一 不能居中  wx-charts在适配上要怎么处理

**Comment by xiaolin3303** [comment]
@sider666  可以使用微信提供的API `wx.getSystemInfo` 获取屏幕的宽度然后做动态的调整

**Comment by sider666** [comment]
在pie图中dataLabel属性没有作用  如果想对图表下方的标识做隐藏 wx-charts是否有参数可以直接设置

**Comment by xiaolin3303** [comment]
@sider666 你说的是`legend`吧，opts里面加上`legend: false`即可，这个参数文档里面漏了

**Comment by sider666** [comment]
pie图的dataLabel属性貌似不起作用

**Comment by xiaolin3303** [comment]
pie图的`dataLabel`还在开发中，这个涉及到文案的检测碰撞问题，稍微有点复杂
