### ISSUE TITLE
X轴样式问题

### ISSUE THREAD

**Issue by Bleoo** [xiaolin3303/wx-charts#30]
![gshb e65 2 64tz6g hu q](https://cloud.githubusercontent.com/assets/11569795/22012743/a041afe2-dcd0-11e6-9921-b59288d4620b.png)

y轴能不能有这种样式，我理解为时刻轴，各个时刻的数据
你给的只能是我理解为合计轴，比如一年的总体数据

**Comment by xiaolin3303** [comment]
没太明白什么意思

**Comment by Bleoo** [comment]
那能实现这种Y轴样式吗

**Comment by Bleoo** [comment]
抱歉，我描述错了。应该是X轴
X轴能否实现上述的时刻样式。
比如14点钟(时刻)的心率值，X轴上应该是对应刻度的。
而现在的样式只能是README中给出的合计表的X轴样式，类似年度合计

**Comment by xiaolin3303** [comment]
这样啊，我说我始终没有看懂，这个可以实现，保持关注吧~

**Comment by xiaolin3303** [comment]
增加配置
```
// X轴网格为刻度样式
opts.xAxis.type: 'calibration'
```
