### ISSUE TITLE
折线图数据格式问题

### ISSUE THREAD

**Issue by Bleoo** [xiaolin3303/wx-charts#31]
折线图是否能更换成
data:{[
  [x1,y1], [x2,y2]
]}传递坐标的方法，
因为我的点可能是跳跃的，比如14时有数据，但是15时没有，然后16时有数据，我希望14时的点直接点连到16时的点

**Comment by CasoMemory** [comment]
@Bleoo 你好，因为做过很多次图形显示，给你个建议哈。对于你说的那种情况，我建议是最好不要直接连在一起，因为之所以要图形显示，就是根据图形的走势去分析一个趋势的，如果连在一起，某些时候是反映不出来趋势所在。所以，建议如果是没有数据的情况，可以保留显示。

**Comment by CasoMemory** [comment]
@xiaolin3303 同时，也想给博主提一个功能需求，就是数据也可以传递这个字符串 ‘-’ 。因为某些时候，如楼上的朋友所说，可能会出现数据断点，由于所有的数据都必须是数字，而数据断点的时候也不能重置数据为0呀，这个时候如果可以让图形不描绘出该点，同时也能显示该点的数据为 ‘-’ ，那么下一次的点就是可以从有数据的地方开始，这样也能凸显出该点反应的一种具体情况。效果就是如Echarts中那样，可以参考一下。

**Comment by Michly1991** [comment]
我也遇到了相同的折线图问题，需求和 @Bleoo 是一样的，由于我的横坐标是日期，但是要跳过非工作日，所以如果是'-'的话会打断整体的趋势，

**Comment by Bleoo** [comment]
所以，我感觉对于不同需求，图表展示都大不同

**Comment by Michly1991** [comment]
我也建议最好可以传坐标[x,y]，同时横坐标有key和value，显示的是key，当value和x一样时就在该位置绘制点

**Comment by xiaolin3303** [comment]
@Bleoo @Michly1991 如果你们部分没有数据而且不想图表出现断点 可以把没有数据的部分从横坐标中剔除掉

@CasoMemory  目前`wxCharts`确实不支持断点的支持，后续会添加这个功能，感谢你的建议

**Comment by Michly1991** [comment]
@xiaolin3303 横坐标剔除的话，图表显示是否就会不均匀，比如本来是[1,2,3,4,5,6]图像间隔为1，现在是[1,2,3,6],图像前面的间隔为1，但有一个3的跳跃，图表上理应也横向跨越3，但实际4，5是没有数据的，所以也不该在4,5的横坐标上显示点

**Comment by Bleoo** [comment]
@Michly1991  赞同，所以希望 @xiaolin3303 大神尽快支持一下断点功能吧

**Comment by xiaolin3303** [comment]
数据点支持传入`null`, 图表将出现断点
