### ISSUE TITLE
line型图，如果每一个点的数据都为0时，opts.yAxis.min Number Y轴起始值min不生效，例如设置的min=0，但是会显示负数。

### ISSUE THREAD

**Issue by tustman** [xiaolin3303/wx-charts#329]

**Comment by huanghaodong** [comment]
修改getYAxisTextList方法
`function getYAxisTextList(series, opts, config) {
    var data = dataCombine(series);
    // remove null from data
    data = data.filter(function (item) {
        return item !== null;
    });
    var minData = Math.min.apply(this, data);
    var maxData = Math.max.apply(this, data);
    if (typeof opts.yAxis.min === 'number') {
        minData = Math.min(opts.yAxis.min, minData);
    }
    if (typeof opts.yAxis.max === 'number') {
        maxData = Math.max(opts.yAxis.max, maxData);
    }

    // fix issue https://github.com/xiaolin3303/wx-charts/issues/9
    if (minData === maxData && maxData != 0) {
      var rangeSpan = maxData || 1;
      minData -= rangeSpan;
      maxData += rangeSpan;
    }else if( minData == 0 && maxData == 0 ){
      maxData = 1;
      minData = 0;
    }

    var dataRange = getDataRange(minData, maxData);
    var minRange = dataRange.minRange;
    var maxRange = dataRange.maxRange;

    var range = [];
    var eachRange = (maxRange - minRange) / config.yAxisSplit;

    for (var i = 0; i <= config.yAxisSplit; i++) {
        range.push(minRange + eachRange * i);
    }
    return range.reverse();
}`

**Comment by tustman** [comment]
@huanghaodong 谢谢你的回复，已经改好可用了
