### ISSUE TITLE
图表没有数据的时候，图表会卡死

### ISSUE THREAD

**Issue by zuccling** [xiaolin3303/wx-charts#33]

**Comment by zuccling** [comment]
折线图表

**Comment by hr1992** [comment]
饼图也会有同样问题，整个app都卡死。

**Comment by xiaolin3303** [comment]
请具体描述下

**Comment by hr1992** [comment]
@xiaolin3303 当饼图的各项数据为0的时候，会进入死循环。

**Comment by xiaolin3303** [comment]
@hr1992 我这边不能复现这个问题，请确保你使用了最新版本的代码

**Comment by guaicaiboshi** [comment]
这个假死的情况一致存在，请问下是否已经解决了呢？如果要重现很简单，在提供的demo中，部分修改代码：
` createSimulationData1: function () {
      var categories = [];
      var data = []; 
      return {
        categories: categories,
        data: data
      }
    },
    updateData: function () {
      var simulationData = this.createSimulationData1();
        var series = [{
            name: '成交量1',
            data: simulationData.data,
            format: function (val, name) {
                return val.toFixed(2) + '万';
            }
        }];
        lineChart.updateData({
            categories: simulationData.categories,
            series: series
        });
    },`
只要做如上修改，便会重现！

**Comment by gytai** [comment]
这个问题一直在 现在还在死机中

**Comment by daodaocheng** [comment]
@xiaolin3303 绘制的折线图正常有数据时是这样的，默认一个图表最多显示七个数据。
![qq 20181017091257](https://user-images.githubusercontent.com/41509083/47056179-c6595e00-d1ed-11e8-8d06-d81ddac09cb4.png)但现在在选定的日期向前推七天都没有数据的时候就会出现空白，
![qq20181017091448](https://user-images.githubusercontent.com/41509083/47056284-26500480-d1ee-11e8-8f79-eab628e577ad.png)并且页面其他位置的组件以及上级页面都无法响应，再次编译会出现卡死的现象。![qq20181016090548](https://user-images.githubusercontent.com/41509083/47056365-89da3200-d1ee-11e8-8b30-d17782830817.png)之前没有数据的时候只是会显示一个没有数据的图表但canvas不是空的，而且其他组件也不会卡死。自从新增了一个有图表的页面以后就出现了卡死问题，希望可以有办法解决

**Comment by slimvan** [comment]
我也遇到了这个问题，我需要给图表一个默认空的值，在请求到数据后改变图标的数据，但是空数据设置为0时，手机和开发工具都会卡死。

**Comment by logyoo** [comment]
> 我也遇到了这个问题，我需要给图表一个默认空的值，在请求到数据后改变图标的数据，但是空数据设置为0时，手机和开发工具都会卡死。

这个问题解决了吗？我也碰到了

**Comment by marren06** [comment]
我也遇到了,请求成功回调页面 new wxCharts  数据卡死！！！  不能再异步回调new吗？

**Comment by zhouzhuo810** [comment]
series:[] 就会卡死 @xiaolin3303

**Comment by a857430369** [comment]
series = [{
      name: "L4",
      data: [],
      format: function (val) {
        return val.toFixed(2);
      }
    },
  ]
  
  data为空时，会卡死

**Comment by pChao3** [comment]
那就不要让data为空数组，判断一下，为空时置灰显示灰色图案  
series: isEmpty ? [{ data: 100, color: 'gray' }] : data, // 无数据时显示全灰
