### ISSUE TITLE
！！！建议line图可拖动情况下，支持x轴宽度伸缩控制

### ISSUE THREAD

**Issue by zjj1998** [xiaolin3303/wx-charts#386]
看了您的部分源码，觉得可以在开启滚动条件方法下，对画的的x轴点宽度进行修改，将传入的画布大小放大或缩小，而不修改原始画布大小。或者在画x轴点的方法中，对是否开启滚动进行判断，后处理x轴点的宽度。
_仅仅只看了您的部分代码，对您源码的逻辑理解浅薄。希望我挖坟能够成功。_
![image](https://user-images.githubusercontent.com/42028814/63509093-e17fb300-c50d-11e9-8e6c-5e9f5174771d.png)
![image](https://user-images.githubusercontent.com/42028814/63509108-ec3a4800-c50d-11e9-9100-7ccc5db89373.png)
我会尝试进行添加功能，如果能够成功 希望能合并

**Comment by zjj1998** [comment]
@xiaolin3303

**Comment by 16cheng** [comment]
可以试一下uCharts，基于wxcharts改造https://gitee.com/uCharts/uCharts

**Comment by zjj1998** [comment]
> 可以试一下uCharts，基于wxcharts改造https://gitee.com/uCharts/uCharts

谢谢，但基于wecharts我已经实现功能了，以后再用到统计图会选择ucharts的(●'◡'●)
