### ISSUE TITLE
line型图相邻数据落差比较大的时候，例如1278718与0，会导致1278718与0之间的图表过渡的时候到负值

### ISSUE THREAD

**Issue by yangyanju** [xiaolin3303/wx-charts#388]
数值都是正值，设置y轴min为0，但是由于数据落差比较大，比如数据为[80518811, 25425137, 48411828, 48670016, 34476923, 116134596, 1278718, 0, 0, 0, 0, 0],就会导致1278718与0之间的图表过渡的时候到负值。
![image](https://user-images.githubusercontent.com/7056767/63734998-f7e09280-c8b0-11e9-9efa-12b20ac88727.png)
可以看见7月和8月的数据中间有一小段到了负值。这个怎么解决啊，大神指点一下，谢谢了！

**Comment by zjj1998** [comment]
wecharts并没有实现y轴数据抽稀，换个图表插件吧
