### ISSUE TITLE
是否能纵向显示x轴，横向显示y轴

### ISSUE THREAD

**Issue by Bleoo** [xiaolin3303/wx-charts#41]
是否能纵向显示x轴，横向显示y轴
把xy轴互换
![u 380929296 2144584543 fm 23 gp 0](https://cloud.githubusercontent.com/assets/11569795/22813440/9bf808be-ef86-11e6-9345-2828bee525b7.jpg)

**Comment by xiaolin3303** [comment]
暂不支持这个功能哦，后续可能会考虑开发
