### ISSUE TITLE
canvas层级太高真机上会有bug

### ISSUE THREAD

**Issue by linqingmo** [xiaolin3303/wx-charts#42]
canvas层级最高，在真机上会盖住弹出的view，这个要怎么解决？

**Comment by xiaolin3303** [comment]
微信官方有这样的说法:
> canvas 组件是由客户端创建的原生组件，它的层级是最高的。

所以说不管z-index设置多高，canvas总是在它的上面

针对你的情况可以这样设置：
当弹出浮层时，设置canvas的`display:none`
