### ISSUE TITLE
该项目还有人维护吗

### ISSUE THREAD

**Issue by 0x3c** [xiaolin3303/wx-charts#421]
最后提交三年前，是这个项目太稳定还是没人维护了

**Comment by zyzkevin** [comment]
同问

**Comment by yxyufo110** [comment]
文档都没有，哈哈

**Comment by rotd01** [comment]
![image](https://user-images.githubusercontent.com/29349504/99509469-c32e8e80-29c0-11eb-8f76-461ba42e4246.png)
得需要你自己维护,看我自己魔改的小程序

![image](https://user-images.githubusercontent.com/29349504/99509687-0ee13800-29c1-11eb-9e1a-9a20cec0b2f1.png)

**Comment by echo-ho** [comment]
> ![image](https://user-images.githubusercontent.com/29349504/99509469-c32e8e80-29c0-11eb-8f76-461ba42e4246.png)
> 得需要你自己维护,看我自己魔改的小程序
> 
> ![image](https://user-images.githubusercontent.com/29349504/99509687-0ee13800-29c1-11eb-9e1a-9a20cec0b2f1.png)

优秀，我很急。来不及优化了。有没有现成demo?

**Comment by rotd01** [comment]
> > ![image](https://user-images.githubusercontent.com/29349504/99509469-c32e8e80-29c0-11eb-8f76-461ba42e4246.png)
> > 得需要你自己维护,看我自己魔改的小程序
> > ![image](https://user-images.githubusercontent.com/29349504/99509687-0ee13800-29c1-11eb-9e1a-9a20cec0b2f1.png)
> 
> 优秀，我很急。来不及优化了。有没有现成demo?

你可以联系我VX： wangkun7991
