### ISSUE TITLE
请问 measureText 中的各种数值是怎么来的？

### ISSUE THREAD

**Issue by 2984465697** [xiaolin3303/wx-charts#43]
7， 5.5 ， 2.7 ....
是怎么测试出来这些值？换字体也可以吗？

**Comment by xiaolin3303** [comment]
这些都是手动量出来的，微信小程序里面canvas不能设置字体，使用的是系统默认字体，理论上来说不同的系统字体会有差别（差别应该不大），这里是兼容了最常用的系统字体情况
