### ISSUE TITLE
图表怎么重绘

### ISSUE THREAD

**Issue by LuHaoPeng** [xiaolin3303/wx-charts#47]
不知道我这个问题会不会太低级啊哈哈。。。

就是假如我要改动一些数据，然后重新绘制，应该怎么做。

可以直接再new wxCharts()吗，那前一个wxCharts对象会继续占用内存吗？

**Comment by xiaolin3303** [comment]
直接调用`new wxCharts()`即可

**Comment by xiaolin3303** [comment]
@LuHaoPeng 刚添加了`updateData`方法，具体见`README`
