### ISSUE TITLE
我觉得可以增加动画complete回调接口和stopAnimation函数

### ISSUE THREAD

**Issue by LuHaoPeng** [xiaolin3303/wx-charts#48]
因为我现在碰到的一个应用场景，就是在切换自定义标签的时候，就会重绘一次图表（切换了数据源），如果这时候切换标签的速度过快，就会短时间里多次新建wxChart，然后控件就开始闪烁然后绘出结果。
所以我在想是不是如果支持**animation complete回调接口**以及**stopAnimation函数**的话，就可以自己控制动画了。

**Comment by xiaolin3303** [comment]
感谢你的建议，已增加对应方法，具体查看`README`
