### ISSUE TITLE
关于微信charts.js中的折线图、柱状图的双轴加载

### ISSUE THREAD

**Issue by CasoMemary** [xiaolin3303/wx-charts#5]
在公司的项目中，有用到过百度的Echarts插件，对chats类内部的一些属性设置有一些了解。目前在微信的charts.js中，查看了一些相关的配置信息，基本的图表加载是十分流畅的。由于一些原因，需要用charts.js来绘制双轴的图表，比如双X+单Y，或者双Y+单X，亦或双X+双Y的情况；charts.js中关于yAxis的设置只是一个object对象，可能不太会满足双轴的需求。在百度的Echarts插件中，其xAxis和yAxisdo都是一个数组，里面可以依次放置两个对象，分别来表示下上的X轴和左右的Y轴。
       因此，博主可以考虑下增加这个需求的实现吗？

**Comment by xiaolin3303** [comment]
@CasoMemary 你好，如你所说，目前wx-charts确实是不支持双轴的显示，当时设计的初衷是做一个精简的图表工具，满足基本的需求，因为微信小程序对整体项目代码量也有限制，所以这个工具尽量保持小巧，如果有更多的人有双轴的需求的话，会考虑加入，请保持关注~

目前对于你的需求来说，可以fork我的项目，自行进行这个需求的开发，代码整体来说不复杂。

**Comment by CasoMemary** [comment]
@xiaolin3303 好的，那我明白了，会一直关注的，感谢博主的分享。

**Comment by lys623** [comment]
我这边也有类型双轴的需求，持续关注。
