### ISSUE TITLE
什么时候能支持点击事件啊

### ISSUE THREAD

**Issue by hefeng123h** [xiaolin3303/wx-charts#50]
什么时候能支持点击事件啊 求求求

**Comment by xiaolin3303** [comment]
点击之后你需要做什么？
现在有个问题 由于微信小程序框架自身的限制，`wxCharts`工具本身是拿不到`canvas`的`touch`事件，只能在模板和page中自行定义，所以暂时没有支持这个功能

**Comment by hefeng123h** [comment]
@xiaolin3303
我想做一个点击柱状图的某柱 然后重新加载一个跟此柱有关的柱状图 有没有办法做到啊，

**Comment by xiaolin3303** [comment]
新增了对应的方法，具体可参考[wx-charts-demo](https://github.com/xiaolin3303/wx-charts-demo)中`column`图示例
