### ISSUE TITLE
关于x或y轴过滤显示数据

### ISSUE THREAD

**Issue by althyman** [xiaolin3303/wx-charts#51]
你好。 请问是否可以在line折线图x或y轴上过滤显示数据？
比如：x轴数据 [1,2,3....100],      y轴数据[20160101,20160102,20160103...20160331]
我可以通过自定义的filter来过滤显示在x或y上只显示3到5个值显示出来，其它值隐藏。   
最终所呈现的折线图，实际每个点与每条线都需要绘制出来。
谢谢～

**Comment by czh628** [comment]
请问楼上的兄弟解决在x轴或者y轴上显示特定点的问题吗？

**Comment by xiaolin3303** [comment]
@althyman 你上面描述的x(横轴), y(纵轴)轴是不是反了？

**Comment by xiaolin3303** [comment]
y(纵)轴的刻度是系统根据你传入的值自动确定的，暂时没有办法实现自定义过滤显示，关于x轴的过滤显示，你可以设置`categories`中不需要显示的项为空字符串即可

**Comment by zhuyunxia** [comment]
怎么y轴传入数据，具体案例

**Comment by lxhcool** [comment]
如何一开始展示最右侧数据，在线等

**Comment by yatessss** [comment]
> @xiaolin3303 关键是这个设为空字符串的时候存在问题，由于原先插件就有稀释的功能，结果我想要显示的点无法显示了

https://github.com/xiaolin3303/wx-charts/blob/6fafc91fa1981b10eedfb039a8ba2b660715c67a/src/components/draw.js#L280  这里是抽稀的处理，可以自己改库加一个参数去控制

**Comment by benson-xzw** [comment]
可以去掉抽希处理嘛

**Comment by benson-xzw** [comment]
修改x轴的抽希间隔数， 在框架中搜索 var ratio = Math.ceil(categories.length / maxXAxisListLength); 修改ratio值就好

**Comment by zlhpipi** [comment]
可以在点击折线图时，变成可滑动状态吗？
