### ISSUE TITLE
图表无法随scroll-view滚动

### ISSUE THREAD

**Issue by ooyanglinoo** [xiaolin3303/wx-charts#52]
我发现在canvas绘制图表后，图表绘制的位置就固定了，无法跟随scroll-view滚动。下面是我的canvas设置以及new wxcharts截图。
![1](https://cloud.githubusercontent.com/assets/3050438/23161119/d3d83d18-f863-11e6-84e2-a260490f3eac.png)
![2](https://cloud.githubusercontent.com/assets/3050438/23161124/d4e440b2-f863-11e6-8bc3-8a39fd5dda2c.png)

**Comment by xiaolin3303** [comment]
参考微信小程序官方关于`canvas`的说明，[Bug & Tip部分](https://mp.weixin.qq.com/debug/wxadoc/dev/component/canvas.html#canvas)
