### ISSUE TITLE
折线图数据碰撞问题

### ISSUE THREAD

**Issue by zs2402923847** [xiaolin3303/wx-charts#54]
![image](https://cloud.githubusercontent.com/assets/16568341/23498167/4a61f9f2-ff61-11e6-887d-60af962d9df5.png)，数据一密集就很尴尬了
请问能不能实现点击数据点垂直方向区域，弹出提示层，在那上面写数据呢

**Comment by xiaolin3303** [comment]
@zs2402923847 `tooltip`功能正在开发中，请保持关注

**Comment by xiaolin3303** [comment]
已添加`tooltip`功能，具体参数参看`README`或者[wx-charts-demo](https://github.com/xiaolin3303/wx-charts-demo)中`column`图示例
