### ISSUE TITLE
切换tab，出现bug

### ISSUE THREAD

**Issue by NiceChat** [xiaolin3303/wx-charts#55]
tab1中有charts tab2中无，tab1->tab2,然后tab2->tab1 charts消失。

**Comment by xiaolin3303** [comment]
切换tab你做了什么操作？请具体描述下

**Comment by NiceChat** [comment]
`<view class="worth__content" wx:if="{{ tab == 'worth'}}">
      <view class="canvas">
        <text class="canvas--title">净值走势图</text>
        <view class="canvas--content">
          <canvas canvas-id="lineCanvas" class="canvas2" bindtouchstart="touchHandler"></canvas>
        </view>
      </view>
      <view>
   <view>
`
就有一层if判断。 我没有深入分析原因，看表象就给你提了issue。 如不能复现bug，那可能是我的原因。

**Comment by xiaolin3303** [comment]
这个其实已经超出了这个项目的讨论范围
wx:if会销毁DOM元素，所以你再次切回来的时候是一个新的canvas，当然里面是没有内容的，建议你使用`display:none`来隐藏你的tab
good luck

**Comment by li305263** [comment]
赞,换了display 解决了

**Comment by czzerone** [comment]
@li305263  你好，我也出现了你这种情况，我想问一下你最后改的代码是怎么改的，display那个代码是要放在哪里呢
