### ISSUE TITLE
dataItem.color  这个颜色不管用。。。 我用的是area 类型图

### ISSUE THREAD

**Issue by zzjangular** [xiaolin3303/wx-charts#6]
dataItem.color  这个颜色不管用。。。 我用的是area 类型图

**Comment by xiaolin3303** [comment]
@zzjangular 我这边测试是没问题的，请提供下你的配置参数

**Comment by zzjangular** [comment]
#ccc

**Comment by zzjangular** [comment]
发现问题了。。。。简写不行的。。。#ccc不行  但是#cccccc 就可以了。。。。麻烦了

**Comment by zzjangular** [comment]
已经解决啦~ 在git上我已经指出来了

在 2016-12-15 22:54:04，"fang" <notifications@github.com> 写道：


@zzjangular 我这边测试是没问题的，请提供下你的配置参数
