### ISSUE TITLE
能支持雷达图吗？

### ISSUE THREAD

**Issue by sskblusky** [xiaolin3303/wx-charts#60]
![image](https://cloud.githubusercontent.com/assets/20197666/23840311/2fc78e28-07df-11e7-9edb-73412d9cda88.png)
能支持雷达图吗？极坐标轴的，做球队对比比较好！

**Comment by xiaolin3303** [comment]
正在开发雷达图，请保持关注~

**Comment by xiaolin3303** [comment]
已添加雷达图类型，具体参看`README`
