### ISSUE TITLE
title不居中

### ISSUE THREAD

**Issue by a27919478** [xiaolin3303/wx-charts#61]
环形图的title不居中，不知道如何解决
![image](https://cloud.githubusercontent.com/assets/19726808/23896091/1188f154-08e3-11e7-8121-df56a1cff55c.png)

**Comment by xiaolin3303** [comment]
由于微信小程序没有提供测量文字宽度的API，所以是自行写程序计算文案的宽度，当然会出现误差，特别是英文和数字的时候，稍后我会加一个参数配置可以让开发者手动修复文案的位置偏移量

**Comment by xiaolin3303** [comment]
新增位置偏移量配置，具体配置参看[参数说明](https://github.com/xiaolin3303/wx-charts/issues/56)

**Comment by a27919478** [comment]
感谢回复

**Comment by cfx1314** [comment]
这个圆环中间的字是怎么加上去的？

**Comment by xiaolin3303** [comment]
`opts.title`, `opts.subtitle`，具体见参数说明
