### ISSUE TITLE
area图表下面的字的颜色怎么控制 & tooltip某种操作后不能正常显示的问题

### ISSUE THREAD

**Issue by LuckyLucien** [xiaolin3303/wx-charts#62]
![image](https://cloud.githubusercontent.com/assets/15663026/23935963/3a100a5c-098a-11e7-9b66-5f6ce646f226.png)
如图中红框圈出来的字的颜色，背景颜色是暗色调，目前黑色的字体显示不太清楚，想换个颜色。谢谢！

**Comment by LuckyLucien** [comment]
我还发现area图的tooltip在微信开发工具上很好用，但是在真机上就第一点击时弹出tooltip，以后再点不起作用，显示的还是第一次的tooltip。

**Comment by zs2402923847** [comment]
我也是，我还以为我是天选之子。。。

**Comment by xiaolin3303** [comment]
新增了legend color配置

例如：
```javascript
{
    ....
    extra: {
        legendTextColor: '#ff0000'
    }
}
```

**Comment by xiaolin3303** [comment]
@LuckyLucien @zs2402923847 tooltip的问题你们的机型是什么，以及你们的具体配置

看来我不是天选之子

**Comment by LuckyLucien** [comment]
我的是华为荣耀7i的手机，具体配置如图

![1](https://cloud.githubusercontent.com/assets/15663026/23988617/ed2c7a3c-0a69-11e7-82e3-0687f902003c.png)

**Comment by xiaolin3303** [comment]
你的代码如何写的呢？

**Comment by LuckyLucien** [comment]
我的tooltip今天好用了，试了几次都好用，好奇怪，我没改代码啊。代码只这样的：
areaChart= new wxCharts({
                canvasId: 'areaCanvas',
                type: 'area',
                categories: dataArr,
                extra: {
                  lineStyle: 'curve',
                  legendTextColor: '#999999'
                },
                dataLabel :false,
                dataPointShape:false,
                  series: [{
                      name: '资金指数',
                      data: fundArr, 
                      format: function (val) {
                          return val;
                      }
                  }, {
                      name: '强势指数',
                      data: strongArr,
                      format: function (val) {
                          return val;
                      }
                  }, {
                      name: '蓄势指数',
                      data: readyArr,
                      format: function (val) {
                          return val;
                      }
                  }],
                  yAxis: {
                    disabled :true,
                      format: function (val) { 
                          return '';
                      }
                  },
                  xAxis: {
                      fontColor: '#999999',
                      gridColor: '#999999'
                  },  
                  width: that.data.winWidth-30,
                  height: 200});

**Comment by zs2402923847** [comment]
![image](https://cloud.githubusercontent.com/assets/16568341/23991475/79500952-0a74-11e7-9b62-ed4756c89b59.png)
华为麦芒4
![Uploading 207150150963883580.png…]()
红米note3
![Uploading 431245786525621169.png…]()
华为P8青春版
经过三台机子的测试，发现一开始当手指点击图表弹出tooltip，然后移出屏幕外时会出现那种现象，不知道是不是失去焦点了
代码是这样
lineChart2 = new wxCharts({
        canvasId: 'lineCanvas2',
        type: 'line',
        categories: time,
        series: [{
          name: '上月合计',
          data: res.preDayPower,
          format: function (val) {
            return val.toFixed(0);
          }
        }, {
          name: '当月合计',
          data: res.dayPower,
          color: '#ffffff',
          format: function (val) {
            return val.toFixed(0);
          }
        }],
        yAxis: {
          format: function (val) {
            return val.toFixed(0);
          },
          min: 0
        },
        width: windowWidth,
        height: windowWidth / 2,
        dataLabel: false,
        dataPointShape: true
      });

**Comment by xiaolin3303** [comment]
你是监听的`bindtouchstart`吗？ 试着在`bindtouchstart`中打印个东西看下真机上是不是每次点击触发了这个事件

**Comment by zs2402923847** [comment]
的确当手指移出屏幕后，就没有响应监听方法

**Comment by xiaolin3303** [comment]
@zs2402923847 移除屏幕是怎么个操作？

**Comment by LuckyLucien** [comment]
我是监听的bindtouchstart ，发现当手指按住area图像上拉屏幕后监听的函数就不打印了，tooltip也不弹出了，再用手指不管按住屏幕哪里，下拉屏幕一下，监听的函数又能打印了，tooltip也可以正常弹出。试了几次，每次都能重现。

**Comment by zs2402923847** [comment]
@xiaolin3303我和小灰灰的现象差不多

**Comment by xiaolin3303** [comment]
两位，我复现了你们说的问题，总结一下就是当在图表区域内滑动造成页面滚动并且造成图表不完全在页面可视区域内时（图表区域外触发的页面滚动不影响）会造成图表`bindtouchstart`失效，目前看来应该是微信小程序内部机制的一个问题，给出一种解决方案

> disable-scroll	Boolean	false	当在 canvas 中移动时，禁止屏幕滚动以及下拉刷新

给`canvas`加上`disable-scroll`属性

**Comment by LuckyLucien** [comment]
给canvas加上disable-scroll属性后 tooltip好用了 ，问题解决了，好棒！

**Comment by zs2402923847** [comment]
我特么就蛋疼了，我那个页面要依次放三个图表，结果disable-scroll属性一加上，全是雷区啊，就中间两个间隔可以滑动屏幕，产品试过后，抓的我一顿侃，“跟你说多少遍了，要把用户当白痴，你滑动的地方这么小，用户会点吗，不会啊，XX，做事要仔细，你们这些年轻人，不要太浮躁，好了，过程我就不问了，你看什么时候能处理好！跟进”，哎，我晕死啊

**Comment by LuckyLucien** [comment]
我能想到的是你可以把三个图表分别放一个页面的三个tab里，不知道这样做 产品满意吗 @zs2402923847

**Comment by zs2402923847** [comment]
@LuckyLucien 他就是要放三排，我之前和他说，点年内条目浮现月表，点月条目浮现天表，我感觉挺好的，问他行不行，他说：“小程序为什么要叫小程序，就是要一目了然，尽可能让用户少点，不要整那些花里胡哨多余操作，不要老是程序员思维，就放三块，堆起来”。。。

**Comment by tangGuoOne** [comment]
tooltip怎么设置才能弹出，怎么我的都不对

**Comment by tangGuoOne** [comment]
我看了上面几楼写的程序，并没有设置toolip

**Comment by tangGuoOne** [comment]
我发现设置了dataLabel: false,
 dataPointShape: true

**Comment by tangGuoOne** [comment]
把标题的字弄大在哪里设置

**Comment by tangGuoOne** [comment]
是不是需要监听bindtouchstart ，监听这个写在程序的哪里

**Comment by LuckyLucien** [comment]
需要监听bindtouchstart @tangGuoOne 
wxml文件的canvas元素：
`<canvas canvas-id="areaCanvas" disable-scroll="false" bindtouchstart="touchHandler" class="area"></canvas>`

在js文件的Page()实例里写：
```
touchHandler:function (e) {
    areaChart.showToolTip(e);
  },
```

**Comment by tangGuoOne** [comment]
我是不是需要在onload的时候就把chart new 好

**Comment by tangGuoOne** [comment]
怎么动态设置categories和series.data

**Comment by LuckyLucien** [comment]
我是在onload的时候先获取的后台数据，拿到数据就new wxCharts()了。     @tangGuoOne

**Comment by tangGuoOne** [comment]
你获取后台数据是用http还是https

**Comment by LuckyLucien** [comment]
当然是https

**Comment by tangGuoOne** [comment]
获取后台数据你不需要传参数吗，onload的时候，参数还没有呢

**Comment by tangGuoOne** [comment]
怎么设置服务器，是不是服务器要安装ssl证书

**Comment by tangGuoOne** [comment]
怎么设置服务器域名啊

**Comment by tangGuoOne** [comment]
tooltip中我想显示x轴数据，怎么设置，例如，x轴是1到10，当我点到5时，tooltip中要出现5加上y轴值

**Comment by LuckyLucien** [comment]
我的代码是这样写的，我改写了wxcharts.js文件的showToolTip函数， 通过给showToolTip函数传不同的参数，来改变tooltip显示的值 @tangGuoOne 
```
touchHandler:function (e) {
  	 console.log(areaChart.getCurrentDataIndex(e));
    areaChart.showToolTip(e,fundTimes,strongTimes,readyTimes);
  },
```

**Comment by tangGuoOne** [comment]
你的showToolTip函数改成了什么样

**Comment by Har-zheng** [comment]
line.getCurrentDataIndex(e) 点击内容区域始终输出 -1值   直接造成showToolTip就不显示对应tip   很奇怪 不知道什么原因
