### ISSUE TITLE
当图表值是动态赋值的时候，使用format 自定义文字内容提示val.toFixed is not a function。

### ISSUE THREAD

**Issue by Hgvar** [xiaolin3303/wx-charts#63]
`// pages/today-num/today-num.js
var wxCharts = require('../../utils/wxcharts.js');
var app = getApp();
var columnChart = null;
var chartData = {
    main: {
        title: '今日访问量',
        data: [0, 0, 0, 0],
        categories: ['00:00-06:00', '06:00-12:00', '12:00-18:00', '18:00-24:00']
    },
    sub: [{
        title: '00:00-06:00访问量',
        data: [0, 0, 0, 0, 0, 0],
        categories: ['00:00-01:00', '01:00-02:00', '02:00-03:00', '03:00-04:00', '04:00-05:00', '05:00-06:00']
    }, {
        title: '06:00-12:00访问量',
        data: [0, 0, 0, 0, 0, 0],
        categories: ['06:00-07:00', '07:00-08:00', '08:00-09:00', '09:00-10:00', '10:00-11:00', '11:00-12:00']
    }, {
        title: '12:00-18:00访问量',
        data: [0, 0, 0, 0, 0, 0],
        categories: ['12:00-13:00', '13:00-14:00', '14:00-15:00', '15:00-16:00', '16:00-17:00', '17:00-18:00']                
    }, {
        title: '18:00-24:00访问量',
        data: [0, 0, 0, 0, 0, 0],
        categories: ['18:00-19:00', '19:00-20:00', '20:00-21:00', '21:00-22:00', '22:00-23:00', '23:00-24:00']
    }]
};

Page({
    data: {
        chartTitle: '今日访问数',
        isMainChartDisplay: true
    },
    // -------------------------------------  
   getData:function(data){
        var that=this;// 这个地方非常重要，重置data{}里数据时候setData方法的this应为以及函数的this, 如果在下方的sucess直接写this就变成了wx.request()的this了
	//取值
    wx.request({
      url: 'https://xxxxxxxx/?m=mobile&a=todayfangwentu',
      data: {
          id:data
      },
      header: {
          'content-type': 'application/json'
      }, // 设置请求的 header
      success: function(res){
          console.log(111);
          console.log(res.data.data);
          var arrReverse = res.data.data.reverse();
         var newArr = new Array(24).fill(0);//24长度的盒子
         var dataArr = new Array();//存放data数组
         for (var i=1;i<=24;i++) {
       		for (var j=0;j<arrReverse.length;j++) {
       			if (i == arrReverse[j].H) {
       				newArr[i-1] = arrReverse[j].count;
       			}
       		}
         }
         while(newArr.length >= 6){
            dataArr.push(newArr.splice(0, 6));
         };
         if(newArr.length != 0){
            dataArr.push(newArr);
         };
         chartData.sub[0].data = dataArr[0];
         chartData.sub[1].data = dataArr[1];
         chartData.sub[2].data = dataArr[2];
         chartData.sub[3].data = dataArr[3];
      }
    })
   },

//    -------------------------
    backToMainChart: function () {
        this.setData({
            chartTitle: chartData.main.title,
            isMainChartDisplay: true
        });
        console.log(chartData.main.categories);
        columnChart.updateData({
            categories: chartData.main.categories,
            series: [{
                name: '访问量',
                data: chartData.main.data,
                format: function (val, name) {
                     
                    return val.toFixed(2) + '个';
                }
            }]
        });

    },
    touchHandler: function (e) {
        
        var index = columnChart.getCurrentDataIndex(e);
        if (index > -1 && index < chartData.sub.length && this.data.isMainChartDisplay) {
            this.setData({
                chartTitle: chartData.sub[index].title,
                isMainChartDisplay: false
            });
            console.log(chartData.sub[index].data);
            columnChart.updateData({
                categories: chartData.sub[index].categories,
                series: [{
                    name: '访问量',
                    data: chartData.sub[index].data,
                    format: function (val, name) {
                        return val.toFixed(2) + '个';
                    }
                }]
            });
        }
    },
     onLoad: function(option){
        this.getData(option.id); //页面id

        var windowWidth = 320;
        try {
          var res = wx.getSystemInfoSync();
          windowWidth = res.windowWidth;
        } catch (option) {
          console.error('getSystemInfoSync failed!');
        }

        columnChart = new wxCharts({
            canvasId: 'columnCanvas',
            type: 'column',
            animation: true,
            categories: chartData.main.categories,
            series: [{
                name: '时间段',
                data: chartData.main.data,
                format: function (val, name) {
                    return val.toFixed(2) + '个';
                }
            }],
            yAxis: {
                format: function (val) {
                    return val + '个';
                },
                title: '访问数',
                min: 0
            },
            xAxis: {
                disableGrid: false,
                type: 'calibration'
            },
            width: windowWidth,
            height: 300,
        });
    },
   
});`
这是我的源码，可以帮忙分析下具体是什么原因吗？
![qq 20170315195908](https://cloud.githubusercontent.com/assets/26434040/23947505/ff87572a-09b9-11e7-86ae-5644e1141827.png)

**Comment by xiaolin3303** [comment]
![image](https://cloud.githubusercontent.com/assets/8075923/23985402/dd5fd5c8-0a59-11e7-8bab-7aa5fd85e86d.png)

你的数据是字符串，这是不允许的，需要为数字

**Comment by Hgvar** [comment]
谢谢
