### ISSUE TITLE
request 建议在折线图中添加范围区域

### ISSUE THREAD

**Issue by a27919478** [xiaolin3303/wx-charts#66]
如题

**Comment by xiaolin3303** [comment]
由于本人时间有限，请提出issue时注意以下几点:

1、提出前请翻阅历史issue查看是否有相关的内容
2、bug相关的issue请详细描述具体的情况、复现的步骤、截图、真机系统信息以及你的核心配置代码部分，并请添加`bug`标签
3、需求相关的issue请详细描述具体的需求情况，最好附带示意图，并请添加`request feature`标签

谢谢各位的理解和支持

**Comment by a27919478** [comment]
![Uploading 头像.jpg…]()

**Comment by a27919478** [comment]
![photo](https://cloud.githubusercontent.com/assets/19726808/24181305/1e4f55c8-0ef5-11e7-82ed-206a52db6960.JPG)

**Comment by xiaolin3303** [comment]
这个需求目前来看不是特别通用的需求，暂时不考虑添加，谢谢支持
