### ISSUE TITLE
bug updateData方法刷新问题

### ISSUE THREAD

**Issue by a27919478** [xiaolin3303/wx-charts#69]
当页面渲染完毕后，如果我在其他页面更新这个页面数据时并且调用updateData方法，图形并不会更新数据，需要重新描绘后才会更新数据

**Comment by a27919478** [comment]
有偶然性，偶尔刷新偶尔不刷新。。。还有那个中间的title能否超过内圆环时自动换行？

**Comment by xiaolin3303** [comment]
请先进行一下调试，追踪一下实际的问题所在，给出一些调试信息

圆环的title不能自动换行，可以调整字体大小或者图表的大小来控制

**Comment by a27919478** [comment]
就是当数据发生刷新后，调用这个方法并不能刷新数据，只能点击其他tab隐藏，在点击本页面tab重新绘制才行，具体调试信息我也不知道给什么。。。

**Comment by xiaolin3303** [comment]
请需要提供一个必现的操作步骤，不然没有办法定位问题

**Comment by a27919478** [comment]
[chartsTest.zip](https://github.com/xiaolin3303/wx-charts/files/875343/chartsTest.zip)

有一定的几率发生，刚刚我自己试过，大概二十分之一的几率？？我怀疑是渲染的问题

**Comment by xiaolin3303** [comment]
操作另一个页面的canvas行为是否具有可行性请先调研清楚，具体微信小程序页面管理机制我也不是很清楚，最好是在同一个页面操作，你目前的操作方式风险性以及不可控性都比较大。

你的情况涉及到微信对页面的管理机制，已经不是我们图表工具的讨论范围了，

**Comment by a27919478** [comment]
好的，谢谢你的回复
