### ISSUE TITLE
一个Bug

### ISSUE THREAD

**Issue by CasoMemary** [xiaolin3303/wx-charts#7]
你好，博主，我在使用期间，发现一个问题。就是当第二次加载显示图形的时候，发现容易陷入死循环出不来。debug模式下，发现第二次的时候findRange()的函数第一个参数num值为NaN，导致里面的while循环一直执行。追查了下，发现当getYAxisTextList()函数执行的时候，定义minData的方式有些不太明白。就是最后的 Math.min.apply(this, data)具体代表什么意思？还请指点下，谢谢。

**Comment by xiaolin3303** [comment]
先请详细说明一下复现的步骤，包括你的chart配置

关于Math.min.apply(this, data)的问题，直接调用Math.min的话只能挨个的去传值，比如
```javascript
Math.min(x1, x2, x3, ...)
```

使用apply则可以传入一个数组（这里的data），也就是查找数组中的最小值。

**Comment by CasoMemary** [comment]
@xiaolin3303 我找到原因了，配置没问题，而是传的data中有一个值不正确，导致一直陷入死循环。谢谢博主解疑
