### ISSUE TITLE
作者大大可以做一个折线图和曲线图结合的图例吗

### ISSUE THREAD

**Issue by albercy** [xiaolin3303/wx-charts#71]

**Comment by xiaolin3303** [comment]
由于本人时间有限，请提出issue时注意以下几点:

1、提出前请翻阅历史issue查看是否有相关的内容
2、bug相关的issue请详细描述具体的情况、复现的步骤、截图、真机系统信息以及你的相关配置代码部分，并请添加bug标签
3、需求相关的issue请详细描述具体的需求情况，最好附带示意图，并请添加request feature标签

对于一些后续没有跟进的issue我会在一段时间后关闭，谢谢各位的理解和支持

**Comment by albercy** [comment]
例如百度团队开发的echarts[混合图](http://echarts.baidu.com/demo.html#mix-line-bar)，折线图和柱状图组合在一起，然后图表中有两条不同参数的y 轴，谢谢作者大大

**Comment by xiaolin3303** [comment]
暂时不考虑支持这种需求哦，为了保持`wxCharts`的小巧，只会加入一些特别通用的功能

**Comment by jackyon** [comment]
假如有支持这些就爽了。现在的图表功能有些简单

**Comment by geekwill** [comment]
这个需求我觉得很通用啦
