### ISSUE TITLE
request折线图的数据点图形标识是否可单独显示

### ISSUE THREAD

**Issue by a27919478** [xiaolin3303/wx-charts#72]
![1](https://cloud.githubusercontent.com/assets/19726808/24444754/1c7c8252-149a-11e7-86be-596a2a13c60a.JPG)
就比如最上面和最下面的折线无图形表示，只有中间那条有，还有是否可以加个判断，当折线颜色，名称相同时下方标识只显示一个？

**Comment by xiaolin3303** [comment]
无数据的话就自行处理一下把无数据的部分从`series`中剔除掉，关于“是否可以加个判断，当折线颜色，名称相同时下方标识只显示一个”的问题，这个并不是一个通用的需求，而是你业务的一个特殊的需求，所以不考虑添加，建议你对于自身业务特殊的需求可以`fork`项目代码自行修改
