### ISSUE TITLE
动画卡住的问题

### ISSUE THREAD

**Issue by a27919478** [xiaolin3303/wx-charts#78]
快速的切换两个页面时就会出现这种状况，我本来的想法是在这个页面被隐藏时调用stopAnimation()，结果还是出现该问题
![a](https://cloud.githubusercontent.com/assets/19726808/24906565/c3103b40-1eea-11e7-86a8-f22bd938c6e3.JPG)

**Comment by xiaolin3303** [comment]
调用`stopAnimation`的时机是什么，有没有对应的代码？

**Comment by a27919478** [comment]
![image](https://cloud.githubusercontent.com/assets/19726808/24938356/450de722-1f69-11e7-98bd-07f32557d61a.png)

**Comment by xiaolin3303** [comment]
卡住的意思是快速切换后在某一个页面停留住后图表显示不全？

**Comment by a27919478** [comment]
是的，就是在图表还未显示全的时候快速切换到其他页面

**Comment by xiaolin3303** [comment]
@a27919478 你是在PC的开发工具中复现的吗？我在IDE中没有复现这种情况

**Comment by a27919478** [comment]
在真机和PC开发工具都出现这个问题

**Comment by xiaolin3303** [comment]
@a27919478 我这边复现了这个问题，追踪了一下发现当切换页面时前一个页面绘图的进程没有问题，但是页面切换后貌似绘图进程失去了前一个页面canvas的引用或者是微信小程序忽略了对前一个页面canvas的绘图操作。
你之前提到的在`onHide`中执行终止动画操作，我试验了下，`onHide`触发时机并不是页面离开时立即执行，而是下一个页面加载过程中触发，所以这个时机并不是我们需要的在页面即将离开时这个时机。

目前来看从根本上没有太好的解决方案，需要后续关注下微信小程序是否会更新绘图的机制或者提供对应的生命周期。

对于需要绘制图表的操作，建议在`onShow`中进行，这样即使之前的图表未绘制完成，重新后退回到改页面的时候也能够触发重新绘制。
