### ISSUE TITLE
我按照example写的没有出来图形是什么原因呢

### ISSUE THREAD

**Issue by cfx1314** [xiaolin3303/wx-charts#80]
我按照example写的没有出来图形是什么原因呢，是我哪里写错了吗？
这是我的代码：
var wxCharts = require('../../utils/wxcharts.js');
var app = getApp();

new wxCharts({
    canvasId: 'ringID',
    type: 'pie',
    series: [{
        name: 'cat1',
        data: 50
    }, {
        name: 'cat2',
        data: 30
    }, {
        name: 'cat3',
        data: 1
    }, {
        name: 'cat4',
        data: 1
    }, {
        name: 'cat5',
        data: 46
    }],
    width: 360,
    height: 300,
    dataLabel: true
});

<canvas id="ringID"></canvas>

其中utils和pages是同级的，  
运行之后显示是这样的，
<canvasid="ringID"style="display: none;"></canvas>

不涉及wxcharts插件的都显示正常

**Comment by xiaolin3303** [comment]
console里面有什么报错吗？

**Comment by cfx1314** [comment]
没有报错，我知道是什么原因了，我用的是老的代码，微信小程序官方文档中关于canvas有两种文档，组件中的是过时的代码，API中的是最新的，这是最新的写法<canvas canvas-id="canvasId" /> ，这是过时的写法<canvas id="canvasId" />，我就是用了后一种写法，[/捂脸][/捂脸]
