### ISSUE TITLE
折线图当所有值相等的时候会出现如图的情况

### ISSUE THREAD

**Issue by gebin** [xiaolin3303/wx-charts#9]
![qq 20161223092221](https://cloud.githubusercontent.com/assets/2951334/21445258/bc14a9ba-c8f1-11e6-8cb2-69ea933ea533.png)

**Comment by xiaolin3303** [comment]
这种特殊情况的话，建议你设置一个y轴的起点
```javascript
yAxis: {
    // 这儿设置y轴起点从0开始
    min: 0
}
```

**Comment by xiaolin3303** [comment]
@gebin 或者拉一下最新的代码，兼容了这个问题

**Comment by gebin** [comment]
感谢 ，可以了

**Comment by hongweicao** [comment]
数值1.0004,1.0006,1.0005,1.0007,1.0008，这样相差很小的数据体现不出来走势，只是趋近于一条直线

**Comment by CasoMemory** [comment]
@hongweicao 我之前也是碰到类似这种，可以放大数据，或者统一使用百分比，就可以看到趋势了。

**Comment by hongweicao** [comment]
@CasoMemory  好的

**Comment by HugBoomsj** [comment]
所有值都为0的时候Y轴会出现负数，这个大家解决过吗？

**Comment by jiangyanshuang** [comment]
yAxis: {
min: 0
}
我设置成0后当数据为0时负数都出来了  我不想有负数 怎么解？

**Comment by jiangyanshuang** [comment]
if(minData<0){
    minData=0;
  }
加了个判断OK了
