### ISSUE TITLE
x轴label显示不全，调整height无法解决

### ISSUE THREAD

**Issue by zhounewz** [xiaolin3303/wx-charts#98]
看截图
<img width="322" alt="2017-05-25 12 03 00" src="https://cloud.githubusercontent.com/assets/16400882/26413264/ffd2086e-40dd-11e7-8f8b-1623447180d7.png">

**Comment by MartinQAQ** [comment]
在xcss 里面加上   即可
.canvas {
  width: 100%;
  height: 200px;
}

**Comment by xiaolin3303** [comment]
如@MartinQAQ 所说， `wx-charts`配置的`height`需要和wxss文件中对canvas高度的设置相对应，单位为`px`
